"""Application composition and output contracts."""

from capability_agent.application.composition import (
    PreparedApplication,
    PreparedBinding,
    PreparedDomainRuntime,
    prepare_application,
    prepare_domain_runtime,
)
from capability_agent.application.errors import (
    AnswerCommitError,
    ApplicationConfigurationError,
    AuthorityIntegrityError,
    CapabilityAgentError,
    CapabilityRoutingError,
    CapabilityTransportError,
    DomainProjectionError,
    DomainProvisioningError,
    DomainRegistrationError,
    PolicyConflictError,
    PresentationError,
)
from capability_agent.application.manifest import ApplicationManifest
from capability_agent.application.output import (
    ApplicationResult,
    BindingIdentity,
    BoundDomainOutput,
    CoreRunResult,
    FrameworkOutputComposer,
    JsonOutputRenderer,
    OutputRenderer,
    ValidatedDomainOutput,
)
from capability_agent.application.profile import (
    AcceptanceProfile,
    ApplicationPolicy,
    ApplicationProfile,
    CredentialScope,
    DataSharingPolicy,
    DomainBinding,
    ReportShell,
)
from capability_agent.application.registry import DomainProfileFactory, DomainRegistry

__all__ = [
    "AcceptanceProfile",
    "AnswerCommitError",
    "ApplicationConfigurationError",
    "ApplicationManifest",
    "ApplicationPolicy",
    "ApplicationProfile",
    "ApplicationResult",
    "AuthorityIntegrityError",
    "BindingIdentity",
    "BoundDomainOutput",
    "CapabilityAgentError",
    "CapabilityRoutingError",
    "CapabilityTransportError",
    "CoreRunResult",
    "CredentialScope",
    "DataSharingPolicy",
    "DomainBinding",
    "DomainProfileFactory",
    "DomainProjectionError",
    "DomainProvisioningError",
    "DomainRegistrationError",
    "DomainRegistry",
    "FrameworkOutputComposer",
    "JsonOutputRenderer",
    "OutputRenderer",
    "PolicyConflictError",
    "PreparedApplication",
    "PreparedBinding",
    "PreparedDomainRuntime",
    "PresentationError",
    "ReportShell",
    "ValidatedDomainOutput",
    "prepare_application",
    "prepare_domain_runtime",
]
